In [1]:
###################################################
# Data inputs (input processing)
###################################################

import pandas as pd
import yaml
from Model_Functions_v2_111423 import *
year = 2050
# Specify the path to YAML file
yaml_file_path = 'HYPSTAT_scenario.yaml'

# Read the YAML file
with open(yaml_file_path, 'r') as yaml_file:
    yaml_data = yaml.safe_load(yaml_file)
 
# Extract yaml data into variables
firstYear = yaml_data.get('firstYear', None)
lastYear = yaml_data.get('lastYear', None)
timeWindow = yaml_data.get('timeWindow', None)
scenario = yaml_data.get('scenario', None)
truck_size_limit = yaml_data.get('truck_size_limit', None)

interest = yaml_data.get('interest',None)
payback_years = yaml_data.get('payback_years',None)
payback_years_tank = yaml_data.get('payback_years_tank', None)
payback_years_electrolyzer = yaml_data.get('payback_years_electrolyzer',None)

max_imports_ratio = yaml_data.get('max_imports_ratio',None)
import_zones = yaml_data.get('import_zones',None)
overserved_cost = yaml_data.get('hydrogen_overserved_cost',None)

start = yaml_data.get('start', None)
end = yaml_data.get('end', None) 

all_zones = yaml_data.get('all_zones',None)

# Files
demandFiles_paths = yaml_data.get('demandFile', [])
REcostFiles_paths = yaml_data.get('REcostFile', [])
ProductioncostFiles_paths = yaml_data.get('ProductioncostFile', [])
H2DeliveryFile_paths = yaml_data.get('H2DeliveryFile', [])
H2StorageFile_paths = yaml_data.get('H2StorageFile', [])
SupplycurveFolder_paths = yaml_data.get('SupplycurveFolder', [])
Networks_paths = yaml_data.get('NetworksFiles', [])
#LinkdistanceFile_paths = yaml_data.get('LinkdistanceFile', [])
IncentiveFiles_paths = yaml_data.get('IncentiveFiles', [])
StorageCapacityFiles_paths = yaml_data.get('StorageCapacityFiles', [])
StorageLimitsFiles_paths = yaml_data.get('StorageLimitsFiles', [])


# create the year and tech dictionary:
REcostFiles = pd.concat([pd.read_csv(path) for path in REcostFiles_paths], ignore_index=True)
year_tech_dict = {}
for year, group in REcostFiles.groupby('Year'):
    year_tech_dict[year] = list(group['Tech'])


# Supply Curve and Renewable Capacity
all_renewable_profiles,capacities=get_renewable_profiles(year=year,techs = year_tech_dict[year],path=SupplycurveFolder_paths[0],drop_capacity_below=False)

# Demand
demand=get_demand(all_renewable_profiles,year=year, daily_demand=True,freq='h', file_path=demandFiles_paths[0])

In [2]:
all_renewable_profiles

                    Terrestrial Wind                                          \
level_0                           BN        BS                             K
level_1                            0         0         1         2         0
2050-01-01 00:00:00         0.905057  0.823120  0.896538  0.904083  0.044210
2050-01-01 01:00:00         0.890712  0.818643  0.896331  0.900903  0.082916
2050-01-01 02:00:00         0.899008  0.827902  0.841264  0.891613  0.118951
2050-01-01 03:00:00         0.889998  0.836339  0.804798  0.898724  0.051018
2050-01-01 04:00:00         0.893133  0.835601  0.808986  0.894992  0.006290
...                              ...       ...       ...       ...       ...
2050-12-31 19:00:00         0.145484  0.907677  0.907660  0.907677  0.000000
2050-12-31 20:00:00         0.137526  0.907076  0.907568  0.907565  0.000000
2050-12-31 21:00:00         0.138393  0.905019  0.907496  0.907677  0.000059
2050-12-31 22:00:00         0.130675  0.876657  0.876765  0.905124  0.002116
2050-12-31 23:00:00         0.123516  0.837337  0.890921  0.901460  0.025079

                    Offshore Wind               Solar                      \
level_0                         K         J         A         K         E
level_1                         0         0         0         0         0
2050-01-01 00:00:00      0.873561  0.873561  0.096685  0.081996  0.000000
2050-01-01 01:00:00      0.873561  0.873561  0.089859  0.081868  0.000000
2050-01-01 02:00:00      0.873561  0.873561  0.098689  0.083464  0.000000
2050-01-01 03:00:00      0.873561  0.873561  0.100034  0.084820  0.000000
2050-01-01 04:00:00      0.873561  0.873561  0.091473  0.084905  0.000000
...                           ...       ...       ...       ...       ...
2050-12-31 19:00:00      0.676250  0.676250  0.244527  0.446832  0.072959
2050-12-31 20:00:00      0.811321  0.811321  0.193583  0.299333  0.196108
2050-12-31 21:00:00      0.845572  0.845572  0.187470  0.125804  0.039204
2050-12-31 22:00:00      0.844905  0.844905  0.101074  0.083684  0.000000
2050-12-31 23:00:00      0.845712  0.845712  0.100011  0.083801  0.000000


level_0                    CN        BN        EN
level_1                     0         0         0
2050-01-01 00:00:00  0.061557  0.000000  0.045000
2050-01-01 01:00:00  0.061557  0.000000  0.043362
2050-01-01 02:00:00  0.061557  0.000000  0.045064
2050-01-01 03:00:00  0.061557  0.000000  0.045119
2050-01-01 04:00:00  0.061557  0.000000  0.045119
...                       ...       ...       ...
2050-12-31 19:00:00  0.171139  0.374711  0.162853
2050-12-31 20:00:00  0.212331  0.382633  0.115882
2050-12-31 21:00:00  0.066225  0.141221  0.042990
2050-12-31 22:00:00  0.012487  0.000000  0.040361
2050-12-31 23:00:00  0.060453  0.000000  0.040302

[8760 rows x 13 columns]

In [3]:
capacities

     Terrestrial Wind            Offshore Wind             Solar         \
zone               BN    BS    K             J        K        A     BN
0                59.0  46.0  1.0       24711.0  16474.0  15583.0  951.0
1                 NaN  14.0  NaN           NaN      NaN      NaN    NaN
2                 NaN  26.0  NaN           NaN      NaN      NaN    NaN


zone      CN      E       EN       K
0     1869.0  198.0  19802.0  2444.0
1        NaN    NaN      NaN     NaN
2        NaN    NaN      NaN     NaN

In [4]:
from Model_Functions_v2 import *
supply_path = 'Test case data/Supply profiles'
techs = ['Terrestrial_Wind','Offshore_Wind','Solar']
all_renewable_profiles,capacities=get_renewable_profiles(year=year,techs=techs, drop_capacity_below=False,path=supply_path)

In [5]:
capacities

     Terrestrial_Wind            Offshore_Wind             Solar         \
zone               BN    BS    K             J        K        A     BN
0                59.0  46.0  1.0       24711.0  16474.0  15583.0  951.0
1                 NaN  14.0  NaN           NaN      NaN      NaN    NaN
2                 NaN  26.0  NaN           NaN      NaN      NaN    NaN


zone      CN      E       EN       K
0     1869.0  198.0  19802.0  2444.0
1        NaN    NaN      NaN     NaN
2        NaN    NaN      NaN     NaN

In [6]:
year_tech_dict[year]

['Terrestrial Wind', 'Offshore Wind', 'Solar']

In [7]:
end

'7 Jan '

In [8]:
# Network Links
from Model_Functions_v2_111423 import *
link_flow_direction, links, all_zones,links_to_zones=get_links(path=Networks_paths[0])
delivery_cost=pd.read_csv(H2DeliveryFile_paths[0])
delivery_cost[delivery_cost['Year']==year]
cost_dict = dict(zip(delivery_cost['Delivery Method'], delivery_cost['OPEX ($/kg)']))
links['Transmission Opex ($/kg)'] = links['Delivery Method'].map(cost_dict) * links['Link Distance']/100

all_zones

array(['J', 'NJ1', 'CT1', 'GW', 'CS', 'E', 'HI', 'BN', 'BS', 'K', 'CN',
       'EN', 'A', 'GE', 'F'], dtype=object)

In [9]:
from Model_Functions_v2 import *
links_path = 'Test case data/unlimited_links.csv'
link_flow_direction, links, all_zones,links_to_zones=get_links(links_path,scenario='Best Guess',year=2050)
all_zones

array(['J', 'NJ1', 'CT1', 'GW', 'CS', 'E', 'HI', 'BN', 'BS', 'K', 'CN',
       'EN', 'A', 'GE', 'F'], dtype=object)

In [10]:
for zone in all_zones:
    if zone not in links_to_zones:
        links_to_zones[zone] = set()

In [11]:
build_cost=get_build_cost_matrix(interest,payback_years, payback_years_tank,payback_years_electrolyzer, REcostFiles_paths,ProductioncostFiles_paths,H2StorageFile_paths,year,all_zones)

TypeError: get_build_cost_matrix() takes from 0 to 8 positional arguments but 9 were given

In [ ]:
RE_incentives = pd.read_csv(IncentiveFiles_paths[0])
RE_incentives = RE_incentives[RE_incentives['Year']==year]
ITC = dict(zip(RE_incentives['Tech'], RE_incentives['ITC ($/kg)'].fillna(0)))
PTC = dict(zip(RE_incentives['Tech'], RE_incentives['PTC ($/kg)'].fillna(0)))

In [ ]:
stor_techs = ['Tank','Cavern']
storage_capacities = dict()
for st in stor_techs:
    storage_capacities[st] = dict()

#caverns first, manual for now
for zone in all_zones:
    storage_capacities['Cavern'][zone] = 0

        #now tanks
for zone in all_zones:
        storage_capacities['Tank'][zone] = 'inf'

        #disallow tank storage in HI and J
storage_capacities['Tank']['HI'] = 0
storage_capacities['Tank']['J'] = 0

storage_capacities['Cavern']['CS'] = 8000000

        #now set total storage capacities, again manual for now
Total_storage_capacity = dict()
Total_storage_capacity['Tank'] = 'inf'
Total_storage_capacity['Cavern'] = 'inf'
storage_capacities

{'Tank': {'J': 0,
  'NJ1': 'inf',
  'CT1': 'inf',
  'GW': 'inf',
  'CS': 'inf',
  'E': 'inf',
  'HI': 0,
  'BN': 'inf',
  'BS': 'inf',
  'K': 'inf',
  'CN': 'inf',
  'EN': 'inf',
  'A': 'inf',
  'GE': 'inf',
  'F': 'inf'},
 'Cavern': {'J': 0,
  'NJ1': 0,
  'CT1': 0,
  'GW': 0,
  'CS': 8000000,
  'E': 0,
  'HI': 0,
  'BN': 0,
  'BS': 0,
  'K': 0,
  'CN': 0,
  'EN': 0,
  'A': 0,
  'GE': 0,
  'F': 0}}

In [ ]:
storage_capacities = pd.read_csv(StorageCapacityFiles_paths[0]).set_index('Zone')
storage_capacities = storage_capacities.applymap(lambda x: str(x).strip("'").replace('inf', 'inf'))
storage_capacities = storage_capacities.applymap(lambda x: 'inf' if str(x).strip("'") == 'inf' else pd.to_numeric(x, errors='coerce'))

storage_capacities = {index: row.to_dict() for index, row in storage_capacities.iterrows()}

In [ ]:
storage_capacities

{'Cavern': {'A': 0.0,
  'BN': 0.0,
  'BS': 0.0,
  'CN': 0.0,
  'CS': 8000000.0,
  'E': 0.0,
  'EN': 0.0,
  'F': 0.0,
  'GE': 0.0,
  'GW': 0.0,
  'HI': 0,
  'J': 0,
  'K': 0.0,
  'CT1': 0.0,
  'NJ1': 0.0},
 'Tank': {'A': 'inf',
  'BN': 'inf',
  'BS': 'inf',
  'CN': 'inf',
  'CS': 'inf',
  'E': 'inf',
  'EN': 'inf',
  'F': 'inf',
  'GE': 'inf',
  'GW': 'inf',
  'HI': 0,
  'J': 0,
  'K': 'inf',
  'CT1': 'inf',
  'NJ1': 'inf'}}

In [ ]:
max_imports = demand.sum().sum()*max_imports_ratio
#Time controls
all_renewable_profiles=all_renewable_profiles.loc[start+str(year): end+str(year)]

year_ratio=len((all_renewable_profiles).resample('d').first())/365 # used to estimate total costs for year. Just used for testing. 
print(year_ratio)
max_imports *= year_ratio

build_cost=build_cost*year_ratio

0.019178082191780823

In [ ]:
H2_prod_cost = pd.read_csv(ProductioncostFiles_paths[0])
h2_conversion_efficiency = float(H2_prod_cost[H2_prod_cost['Year']==year]['efficiency(kWh/kg)'])

In [ ]:
h2_conversion_efficiency

51.0

In [ ]:
H2_Storage_Limit = pd.read_csv(StorageLimitsFiles_paths[0])
Total_storage_capacity =H2_Storage_Limit[['Storage Tech','capacity']]

In [ ]:
Total_storage_capacity = dict(zip(H2_Storage_Limit['Storage Tech'], H2_Storage_Limit['capacity']))

In [ ]:
Total_storage_capacity

{'Tank': inf, 'Cavern': inf}